version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres_saftonline
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: bd_saftonline
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    
networks:
  postgres_network:
    driver: bridge
